// ─────────────────────────────────────────────────────────────────────────────
// SIGRET-AQP · Paleta cromática
//
// Se reemplaza el morado por defecto de Sneat (#696CFF) por un petrol profundo.
// Criterio: el sistema es un instrumento de análisis territorial, no un panel
// de administración genérico. El petrol lee como cartográfico y deja el
// protagonismo visual al mapa.
//
// La escala de oportunidad (scoreScale) es una rampa secuencial derivada de
// Inferno: perceptualmente uniforme y segura para daltonismo, requisito para
// que la lectura del mapa sea defendible en un contexto académico.
// ─────────────────────────────────────────────────────────────────────────────

export const staticPrimaryColor = '#0E7C86'
export const staticPrimaryDarkenColor = '#0A6871'

// Rampa secuencial para el score de oportunidad (bajo → alto)
export const scoreScale = [
  '#251A4D',
  '#4A1E6B',
  '#7A2A6B',
  '#B23A5B',
  '#DE5D3F',
  '#F08F2E',
  '#F7C948',
]

// Paleta para series de datos categóricas
export const dataViz = [
  '#0E7C86',
  '#E8A33D',
  '#3E7BB6',
  '#C4553D',
  '#5B9279',
  '#8A6BAF',
  '#B08968',
]

export const themes = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'primary-light': '#2A9BA5',
      'secondary': '#5E6E7E',
      'on-secondary': '#fff',
      'secondary-darken-1': '#4E5C6A',
      'secondary-light': '#7C8A98',
      'success': '#12A594',
      'on-success': '#fff',
      'success-darken-1': '#0E8F80',
      'success-light': '#3BBFB0',
      'info': '#3E7BB6',
      'on-info': '#fff',
      'info-darken-1': '#356A9E',
      'info-light': '#6098C9',
      'warning': '#E8A33D',
      'on-warning': '#fff',
      'warning-darken-1': '#D08F2E',
      'warning-light': '#EFB967',
      'error': '#D64545',
      'on-error': '#fff',
      'error-darken-1': '#BC3A3A',
      'error-light': '#E06B6B',
      'background': '#F4F6F7',
      'on-background': '#1B2A32',
      'surface': '#fff',
      'on-surface': '#1B2A32',
      'grey-50': '#FAFBFB',
      'grey-100': '#F4F6F7',
      'grey-200': '#E9EDEF',
      'grey-300': '#DCE2E5',
      'grey-400': '#BAC4CA',
      'grey-500': '#94A2AB',
      'grey-600': '#6F808B',
      'grey-700': '#556570',
      'grey-800': '#3A4750',
      'grey-900': '#1F2A31',
      'grey-light': '#FAFBFB',
      'perfect-scrollbar-thumb': '#D5DCE0',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#FAFBFB',
    },
    variables: {
      'code-color': '#0E7C86',
      'overlay-scrim-background': '#1B2A32',
      'tooltip-background': '#1B2A32',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#1B2A32',
      'border-opacity': 0.14,
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 1,
      'track-bg': '#F4F6F7',
      'shadow-key-umbra-color': '#1B2A32',
      'shadow-xs-opacity': '0.10',
      'shadow-sm-opacity': '0.10',
      'shadow-md-opacity': '0.10',
      'shadow-lg-opacity': '0.10',
      'shadow-xl-opacity': '0.10',
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': '#22A2AD',
      'on-primary': '#fff',
      'primary-darken-1': '#1B8B95',
      'primary-light': '#45BAC4',
      'secondary': '#8497A6',
      'on-secondary': '#fff',
      'secondary-darken-1': '#728594',
      'secondary-light': '#9DAEBB',
      'success': '#1FC0AC',
      'on-success': '#fff',
      'success-darken-1': '#19A896',
      'success-light': '#48D2C1',
      'info': '#5A96CE',
      'on-info': '#fff',
      'info-darken-1': '#4C84B8',
      'info-light': '#7FB0DC',
      'warning': '#F0B45C',
      'on-warning': '#fff',
      'warning-darken-1': '#D89F4C',
      'warning-light': '#F5C983',
      'error': '#E56262',
      'on-error': '#fff',
      'error-darken-1': '#CC5252',
      'error-light': '#EC8686',
      'background': '#131C22',
      'on-background': '#DEE6EA',
      'surface': '#1B262E',
      'on-surface': '#DEE6EA',
      'grey-50': '#20303A',
      'grey-100': '#263843',
      'grey-200': '#2E424F',
      'grey-300': '#3A5261',
      'grey-400': '#4E6A7C',
      'grey-500': '#6C8898',
      'grey-600': '#8DA5B3',
      'grey-700': '#AFC1CB',
      'grey-800': '#CBD8DF',
      'grey-900': '#E6EDF1',
      'grey-light': '#20303A',
      'perfect-scrollbar-thumb': '#3A5261',
      'skin-bordered-background': '#1B262E',
      'skin-bordered-surface': '#1B262E',
      'expansion-panel-text-custom-bg': '#20303A',
    },
    variables: {
      'code-color': '#22A2AD',
      'overlay-scrim-background': '#0C1318',
      'tooltip-background': '#DEE6EA',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#DEE6EA',
      'border-opacity': 0.14,
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 1,
      'track-bg': '#263843',
      'shadow-key-umbra-color': '#000',
      'shadow-xs-opacity': '0.30',
      'shadow-sm-opacity': '0.30',
      'shadow-md-opacity': '0.30',
      'shadow-lg-opacity': '0.30',
      'shadow-xl-opacity': '0.30',
    },
  },
}

export default { themes }
